#........................
# first simple git action
#........................

name: Simple PipeLine

on: 
   push:
      branches:
           -main
jobs:

   my_job1:
      runs-on: ubuntu-latest
      
      
      steps:
      
     - name: Print hello world
       run: echo "HELLO WORLD !!!"
